package modelo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
public interface CriaturasDAO {
	public boolean introducirUser(UserGame user);
	public boolean iniciarSesion(UserGame user);
	public ArrayList<Creature> obtenerPartidas(UserGame user);
	public boolean comprobarUser(UserGame user);
	public boolean eliminarPartida(Creature creature);
	public List<Objetos> verObjectos(Creature creature);
	public ArrayList<Food> listaComida();
	public boolean darComida(Creature criatura, Food comida);
	public boolean irDePaseo(Creature creatureName);
	public Object insertarCriatura(Creature criatura);
	public boolean mirarEmocion(Creature creature);
	public boolean descansar(Creature criatura);
	public boolean equiparObjeto(Creature criatura, Accesory accesorio);
	public boolean quitarObjeto(Creature criatura, Accesory accesorio);
	public boolean quitarCualquierObjeto(Creature criatura);
	public int comprobarObjeto(Creature criatura);
	public boolean desbloqueoBH(Creature criatura);
	public boolean desbloqueoSG(Creature criatura);
	public boolean comprobarBH(Creature criatura);
	public boolean comprobarSG(Creature criatura);
	public Creature obtenerDatosCriatura(int codCreature);
	public boolean efectosAccesorio(Creature creature, Accesory accesory);
}